from .env import JSON, env_first, env_int, env_float, env_truthy
from .text import json_bytes, text_from_content, lane_task_text
from .harness import (_lane_fail_marker_on, lane_unverified_reply, _lane_harness_on,
    parse_harness_result, harness_lane_reply, lane_acceptance_test, _clean_acceptance_command)
from .cost import weighted_cache, classify_miss, append_reasonix_cost, summarize_reasonix_cost
from .levers import (
    # state
    _REASONIX_CLI_SEMAPHORE_LOCK, _REASONIX_CLI_SEMAPHORE,
    _PREINDEX_LOCK, _PREINDEX_DONE, _PREINDEX_NODE_SCRIPT,
    _PRIME_LOCK, _PRIME_GATES,
    _KEEPALIVE_LOCK, _KEEPALIVE_PREFIXES,
    _READ_SUMMARY_CACHE_LOCK, _READ_SUMMARY_CACHE, _READ_CACHE_LOADED,
    READ_CACHE_BLOCK_BEGIN, READ_CACHE_BLOCK_END, _FILE_PATH_RE,
    _PRIME_SERIAL_LOCK, _PRIME_SERIAL_COUNTS, _PRIME_SERIAL_LOCKS,
    _LANE_LOCK, _LANE_COUNTS,
    _SYNTHESIS_INTENT_RE, _READER_INTENT_RE, _EDIT_INTENT_RE, _READER_BROADEN_RE,
    _PREFETCH_PATH_RE, _OVERSCOPE_BULK_RE, _GUIDE_OPEN_MARKER, _GUIDE_CLOSE_MARKER,
    _NEGATION_RE, _BILLING_HEADER_RE,
    # functions
    preindex_enabled, _preindex_node_bin, _preindex_engine_dist, build_preindex,
    gateway_trace, reasonix_cli_semaphore,
    _prime_dict_cap, _evict_oldest,
    _keepalive_enabled, record_keepalive_prefix, keepalive_targets,
    _read_cache_on, _read_cache_cap, _read_cache_ttl_s, _read_cache_max_bytes,
    _read_cache_path, _file_fingerprint, extract_file_paths_from_prompt,
    _read_cache_store, _read_cache_lookup, read_cache_injection_block,
    populate_read_cache, save_read_cache, load_read_cache,
    reset_prime_state, serial_lock_for, acquire_serial_slot,
    register_lane_attempt, should_force_fallback, clear_lane_count,
    prefix_prime_key, acquire_prime_role, model_registry,
    normalize_prefix,
    tool_schema_entries, schema_type, is_structured_output_tool_name,
    _schema_has_nested_array_of_objects,
    _reader_broaden_on, classify_lane_type, is_synthesis_prompt, is_heavy_synthesis,
    mapreduce_directive, context_budget_directive,
    _output_discipline_on, output_discipline_directive, output_discipline_budget,
    _read_summary_on, read_summary_budget, read_lane_summary_instruction,
    _overscope_on, _overscope_max_files, lane_file_scope_count,
    _strip_injected_guide, _bulk_scope_match, overscope_rejection,
)
from .engine_seam import (
    GatewayError,
    anthropic_system_to_text, anthropic_messages_to_openai,
    anthropic_tools_to_openai, anthropic_tool_choice_to_openai,
    openai_response_to_anthropic, estimate_tokens,
    provider_chat_payload, call_openai_compatible,
    fallback_value_from_schema, structured_timeout_fallback,
    structured_output_prompt_instruction, _tool_choice_forces,
    openai_messages_to_prompt, requested_structured_output_tool,
    tool_name_from_schema, tool_names_from_payload,
    structured_output_success_text, anthropic_has_successful_structured_output,
    parse_json_object_from_text, anthropic_tool_use_response,
    anthropic_end_turn_response, retry_cap_for_empty,
    run_reasonix_acp, call_openai_chat_completion,
)
from .server import (
    BaseHTTPRequestHandler, ThreadingHTTPServer,
    ClientGone, Handler, _keepalive_loop, main,
)

# The old gateway path is now a thin shim that re-exports the package surface via
# `from reasonix_gateway import *`. A bare `*` skips underscore-prefixed names, but
# the launcher/MCP/test-suite reference internal symbols (e.g. _KEEPALIVE_PREFIXES,
# _LANE_COUNTS, _keepalive_loop) on the loaded module. List every re-exported name
# in __all__ so `import *` reproduces the full public surface the monolith exposed.
__all__ = [
    "JSON", "env_first", "env_int", "env_float",
    "env_truthy", "json_bytes", "text_from_content", "lane_task_text",
    "_lane_fail_marker_on", "lane_unverified_reply", "_lane_harness_on", "parse_harness_result",
    "harness_lane_reply", "lane_acceptance_test", "_clean_acceptance_command", "weighted_cache",
    "classify_miss", "append_reasonix_cost", "summarize_reasonix_cost", "_REASONIX_CLI_SEMAPHORE_LOCK",
    "_REASONIX_CLI_SEMAPHORE", "_PREINDEX_LOCK", "_PREINDEX_DONE", "_PREINDEX_NODE_SCRIPT",
    "_PRIME_LOCK", "_PRIME_GATES", "_KEEPALIVE_LOCK", "_KEEPALIVE_PREFIXES",
    "_READ_SUMMARY_CACHE_LOCK", "_READ_SUMMARY_CACHE", "_READ_CACHE_LOADED", "READ_CACHE_BLOCK_BEGIN",
    "READ_CACHE_BLOCK_END", "_FILE_PATH_RE", "_PRIME_SERIAL_LOCK", "_PRIME_SERIAL_COUNTS",
    "_PRIME_SERIAL_LOCKS", "_LANE_LOCK", "_LANE_COUNTS", "_SYNTHESIS_INTENT_RE",
    "_READER_INTENT_RE", "_EDIT_INTENT_RE", "_READER_BROADEN_RE", "_PREFETCH_PATH_RE",
    "_OVERSCOPE_BULK_RE", "_GUIDE_OPEN_MARKER", "_GUIDE_CLOSE_MARKER", "_NEGATION_RE",
    "_BILLING_HEADER_RE", "preindex_enabled", "_preindex_node_bin", "_preindex_engine_dist",
    "build_preindex", "gateway_trace", "reasonix_cli_semaphore", "_prime_dict_cap",
    "_evict_oldest", "_keepalive_enabled", "record_keepalive_prefix", "keepalive_targets",
    "_read_cache_on", "_read_cache_cap", "_read_cache_ttl_s", "_read_cache_max_bytes",
    "_read_cache_path", "_file_fingerprint", "extract_file_paths_from_prompt", "_read_cache_store",
    "_read_cache_lookup", "read_cache_injection_block", "populate_read_cache", "save_read_cache",
    "load_read_cache", "reset_prime_state", "serial_lock_for", "acquire_serial_slot",
    "register_lane_attempt", "should_force_fallback", "clear_lane_count", "prefix_prime_key",
    "acquire_prime_role", "model_registry", "normalize_prefix", "tool_schema_entries",
    "schema_type", "is_structured_output_tool_name", "_schema_has_nested_array_of_objects", "_reader_broaden_on",
    "classify_lane_type", "is_synthesis_prompt", "is_heavy_synthesis", "mapreduce_directive",
    "context_budget_directive", "_output_discipline_on", "output_discipline_directive", "output_discipline_budget",
    "_read_summary_on", "read_summary_budget", "read_lane_summary_instruction", "_overscope_on",
    "_overscope_max_files", "lane_file_scope_count", "_strip_injected_guide", "_bulk_scope_match",
    "overscope_rejection", "GatewayError", "anthropic_system_to_text", "anthropic_messages_to_openai",
    "anthropic_tools_to_openai", "anthropic_tool_choice_to_openai", "openai_response_to_anthropic", "estimate_tokens",
    "provider_chat_payload", "call_openai_compatible", "fallback_value_from_schema", "structured_timeout_fallback",
    "structured_output_prompt_instruction", "_tool_choice_forces", "openai_messages_to_prompt", "requested_structured_output_tool",
    "tool_name_from_schema", "tool_names_from_payload", "structured_output_success_text", "anthropic_has_successful_structured_output",
    "parse_json_object_from_text", "anthropic_tool_use_response", "anthropic_end_turn_response", "retry_cap_for_empty",
    "run_reasonix_acp", "call_openai_chat_completion", "ClientGone", "Handler",
    "_keepalive_loop", "main", "BaseHTTPRequestHandler", "ThreadingHTTPServer",
]
